#!/bin/bash

echo "GitHub Push Script"
echo "=================="
echo ""
echo "1. GitHub.com'a gidin"
echo "2. Sağ üstte + işaretine tıklayın > New repository"
echo "3. Repository name: manim-service"
echo "4. Public seçin, Create repository tıklayın"
echo ""
echo "5. Sonra bu komutları çalıştırın:"
echo ""
echo "cd /Users/ruby/Documents/Madlen.io-clone-test1/manim-service-deploy"
echo "git remote remove origin 2>/dev/null"
echo "git remote add origin https://github.com/KULLANICI_ADINIZ/manim-service.git"
echo "git push -u origin main"
echo ""
echo "GitHub kullanıcı adı ve şifrenizi/token'ınızı girmeniz istenecek."
echo ""
echo "Token oluşturmak için:"
echo "GitHub > Settings > Developer settings > Personal access tokens > Generate new token"